# -*- coding: utf-8 -*-
"""FCFS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18HVPe9HR4YnHcGkn1LnbqSCkYtX1sVE-
"""

Arrival_Time=[0, 1, 5, 6]
Burst_Time=[2, 2, 3, 4]
first=Arrival_Time[0] + Burst_Time[0]
Completion_Time=[] 
Completion_Time.append(first) #[2, 4, ]

for i, j in zip(Arrival_Time[1:], Burst_Time[1:]):
  if i <= Completion_Time[len(Completion_Time)-1]:
    Completion_Time. append(Completion_Time[len(Completion_Time)-1]+ j)
  else:
    diff=i-Completion_Time[len(Completion_Time)-1]
    Completion_Time. append(Completion_Time[len(Completion_Time)-1]+ j + diff)
print(Completion_Time)

import pandas as pd

df=pd.DataFrame({"Arrival Time":Arrival_Time, "Burst Time": Burst_Time, "Completion Time": Completion_Time })

df

df["Turn Around Time"]= df["Completion Time"]- df["Arrival Time"]

df["Waiting Time"]= df["Turn Around Time"]- df["Burst Time"]

df